config:
  - category: "Product"
    items:
      - name: "AI Doc Creation"
        url: "/#create"
      - name: "AI Doc Editing"
        url: "/#edit"
      - name: "Real-Time Collaboration"
        url: "/#collaboration"
      # - name: "Doc Templates"
      #   url: "/#templates"
      - name: "Pricing"
        url: "/pricing"
  - category: "Resources"
    items:
      # - name: "Documentation"
      #   url: "/docs"
      - name: "Feature Requests"
        url: "https://spell.featurebase.app/"
      - name: "Product Roadmap"
        url: "https://spell.featurebase.app/roadmap"
      # - name: "Community"
      #   url: "/" 
      # - name: "Solutions"
      #   url: "/solutions" 
      - name: "Writing Guides"
        url: "/resources"
      - name: "FAQs"
        url: "/#faq"
      # - name: "Status"
      #   url: "/status"
  # - category: "Free Tools"
  #   items:
  #     - name: "Essay Writer"
  #       url: "/tools/essay-writer"
  #     - name: "Thesis Writer"
  #       url: "/tools/thesis-writer"
  #     - name: "Business Plans"
  #       url: "/tools/business-plan-writer"
  #     - name: "Executive Summary"
  #       url: "/tools/executive-summary-writer"
  #     - name: "Client Proposal"
  #       url: "/tools/client-proposal-creator" 
  #     - name: "Speech Writer"
  #       url: "/tools/speech-writer" 
  #     - name: "View All →"
  #       url: "/tools"
  # - category: "Use Cases"
  #   items:
  #     - name: "For Universities"
  #       url: "/use-cases/university" 
  #     - name: "For Teams"
  #       url: "/use-cases/teams" 
  #     - name: "For Marketing"
  #       url: "/use-cases/marketing"
  #     - name: "For Product"
  #       url: "/use-cases/product"
  #     - name: "For Sales"
  #       url: "/use-cases/sales"
  #     - name: "For HR"
  #       url: "/use-cases/hr"
  #     - name: "For Education"
  #       url: "/use-cases/education" 
  #     - name: "View All →"
  #       url: "/use-cases"
  - category: "Company"
    items:
      - name: "Why"
        url: "/why"
      - name: "Contact"
        url: "mailto:support@spellapp.com" 
      # - name: "Careers"
      #   url: "/careers"
      # - name: "Partnerships"
      #   url: "/partnerships"
      # - name: "Affiliate Program"
      #   url: "/affiliate" 
      - name: "Privacy Policy"
        url: "/privacy-policy"
      - name: "Terms of Service"
        url: "/terms-of-service"